config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :terms
    resources :phrases_terms
    resources :phrases
  end

  root to: "visitors#index"
  devise_for :users
  resources :users
  resources :phrases do
    resources :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :phrase
  validates :body, presence: true
end

app/models/phrase.rb
# frozen_string_literal: true

class Phrase < ApplicationRecord
  has_and_belongs_to_many :terms
  validates :sentence, presence: true
  has_many :comments, dependent: :destroy
end

app/models/phrase_term.rb
# frozen_string_literal: true

class PhraseTerm < ApplicationRecord
  belongs_to :phrase
  belongs_to :term
end

app/models/phrases_term.rb
# frozen_string_literal: true

class PhrasesTerm < ApplicationRecord
  belongs_to :phrase
  belongs_to :term
end

app/models/term.rb
# frozen_string_literal: true

class Term < ApplicationRecord
  has_and_belongs_to_many :phrases
  validates :word, :meaning, :reading, presence: true
  validates :word , length: { maximum: 255 }
  validates :meaning, length: { maximum: 255}
  validates :reading, length: { maximum: 255 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy

  def username
    return email.split("@")[0].capitalize
  end
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    include Administrate::Punditize

    before_action :authenticate_user!
    before_action :authenticate_admin

    protected

    def authenticate_admin
      unless current_user.admin?
        redirect_to root_path, alert: "Access denied"
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/phrases_controller.rb
 #frozen_string_literal: true

module Admin
  class PhrasesController < Admin::ApplicationController
  end
end

app/controllers/admin/phrases_terms_controller.rb
#frozen_string_literal: true

module Admin
  class PhrasesTermsController < Admin::ApplicationController
  end
end

app/controllers/admin/terms_controller.rb
# frozen_string_literal: true
module Admin
  class TermsController < Admin::ApplicationController
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_phrase
  before_action :authenticate_user!

  def create
    @comment = @phrase.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @comment = @phrase.comments.find(params[:id])
    @comment_id = @comment.id
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :phrase_id)
  end

  def set_phrase
    @phrase = Phrase.find(params[:phrase_id])
  end
end

app/controllers/phrases_controller.rb
# frozen_string_literal: true

class PhrasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_phrase, only: [:show, :edit, :update, :destroy]

  def index
    @phrases = Phrase.all
  end

  def show
    @comment = Comment.new
    @comments = @phrase.comments.order("created_at DESC")
  end

  def new
    @phrase = Phrase.new
  end

  def edit
  end

  def create
    @phrase = Phrase.new(phrase_params)

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to @phrase, notice: "Phrase was successfully created." }
        format.json { render :show, status: :created, location: @phrase }
      else
        format.html { render "new" }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @phrase.update(phrase_params)
        format.html { redirect_to @phrase, notice: "Phrase was successfully updated." }
        format.json { render :show, status: :ok, location: @phrase }
      else
        format.html { render "edit" }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @phrase.destroy
    respond_to do |format|
      format.html { redirect_to phrases_url, notice: "Phrase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_phrase
      @phrase = Phrase.find(params[:id])
    end

    def phrase_params
      params.require(:phrase).permit(:sentence)
    end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, notice: "User updated."
    else
      redirect_to users_path, alert: "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, notice: "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end
end

app/controllers/visitors_controller.rb
# frozen_string_literal: true

class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  [<%= comment.created_at %>]
  <%= comment.user.username %> :
  <% if current_user && current_user == comment.user || current_user.admin? %>
    <%= link_to "Delete", phrase_comment_path(@phrase, comment),
      method: :delete, remote: true, style: 'float: right' %>
    <% end %>
    <%= comment.body %>
    <hr/>
  <br/>
</div>

app/views/comments/create.js.erb
$('#comment_pane').prepend("<%=j render @comment %>");
$('#comment_body').val('');

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').html('');

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Minerva'
    %meta{name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Minerva'}"}
    %link{rel: "stylesheet", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", integrity: "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", crossorigin: "anonymous"}
    = stylesheet_pack_tag "application", media: "all"
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags
  %body
    %header
      = render "layouts/navigation"
    %main{role: "main"}
      = render "layouts/messages"
      = yield
    %script{crossorigin: "anonymous", integrity: "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", src: "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1", src: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"}
    %script{crossorigin: "anonymous", integrity: "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", src: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"}
    = javascript_pack_tag "application"

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/phrases/_form.html.erb
<%= form_with(model: phrase, local: true) do |form| %>
  <% if phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% phrase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sentence %>
    <%= form.text_field :sentence %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phrases/edit.html.erb
<h1>Editing Phrase</h1>

<%= render 'form', phrase: @phrase %>

<%= link_to 'Show', @phrase, class: "btn btn-warning" %> |
<%= link_to 'Back', phrases_path, class: "btn btn-dark" %>

app/views/phrases/index.html.erb
<p id="notice"><%= notice %></p>

<h1> <ins>Phrases </ins></h1>
<%= link_to 'New Phrase', new_phrase_path, class: "btn btn-primary" %>
<hr/>
<table>
  <thead>
    <tr>
      <th>Sentence</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @phrases.each do |phrase| %>
      <tr>
        <td><%= phrase.sentence %></td>
        <td><%= link_to 'Show', phrase, class: "btn btn-warning" %></td>
        <td><%= link_to 'Edit', edit_phrase_path(phrase), class: "btn btn-danger" %></td>
        <td><%= link_to 'Destroy', phrase, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %></td>
        <td><%= pluralize(phrase.comments.count, "Comments") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr/>
<br>

app/views/phrases/new.html.erb
<h1>New Phrase</h1>

<%= render 'form', phrase: @phrase %>

<%= link_to 'Back', phrases_path, class: "btn btn-dark" %>

app/views/phrases/show.html.erb
<p>
  <strong>Sentence:</strong>
  <%= @phrase.sentence %>
</p>
<br/>
<%= link_to 'Edit', edit_phrase_path(@phrase), class: "btn btn-danger" %> |
<%= link_to 'Back', phrases_path, class: "btn btn-dark" %>
<br/>
<br/>

<%= form_with model: [@phrase, @comment], local: true do |f| %>
<%= f.text_field :body %> 
<%= f.submit "Comment" %> 
<% end %>
<hr/>

<div id="comment_pane">
<% @comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
  <% end %>
</div>

app/views/users/_user.html.haml
%td
  = link_to user.email, user
%td
  = form_for(user) do |f|
    = f.select(:role, User.roles.keys.map {|role| [role.titleize,role]})
    = f.submit 'Change Role', :class => 'button-xs'
%td
  = link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr= render user

app/views/users/show.html.haml
%h3 User
%p
  Name: #{@user.name if @user.name}
%p
  Email: #{@user.email if @user.email}

app/views/visitors/index.html.erb
<div class="hero-image">
  <div class="hero-text">
    <h1>Welcome to Menirva</h1>
    <p>Talk your way</p>
    <%= link_to "Login", new_user_session_path, class: "btn btn-success" %>
    <%= link_to "Phrases", phrases_path, class: "btn btn-success" %>
  </div>
</div>